---
# Platform Namespaces

apiVersion: v1
kind: Namespace
metadata:
  name: platform-gitops
  labels:
    app.kubernetes.io/component: gitops

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-ingress
  labels:
    app.kubernetes.io/component: ingress

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-dns
  labels:
    app.kubernetes.io/component: dns

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-observability
  labels:
    app.kubernetes.io/component: observability

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-registry
  labels:
    app.kubernetes.io/component: registry
