---
# Platform Namespaces

apiVersion: v1
kind: Namespace
metadata:
  name: platform-gitops
  labels:
    app.kubernetes.io/component: gitops

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-networking
  labels:
    app.kubernetes.io/component: networking

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-observability
  labels:
    app.kubernetes.io/component: observability

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-registry
  labels:
    app.kubernetes.io/component: registry

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-automation
  labels:
    app.kubernetes.io/component: automation

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-secrets
  labels:
    app.kubernetes.io/component: secrets
