# Registry pull secret for app namespaces
# NOTE: This file is templated by Ansible with secrets from Pulumi
# See: ansible/templates/kubernetes/registry-pull-secret.yaml.j2

# Placeholder - will be replaced by Ansible template
