{{- if .Values.storage }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "platform.name" . }}-data
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s-data/{{ include "platform.name" . }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.infrastructure.nodeName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "platform.name" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: {{ include "platform.name" . }}-data
{{- end }}
