# ArgoCD Application for signews-api
# News processing platform - production deployment

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signews-api-prod
  namespace: platform-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:jterrazz/signews-api.git
    targetRevision: develop
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: app-signews-api-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
