---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
spec:
  secretName: n8n-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - n8n.jterrazz.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  annotations:
    external-dns.alpha.kubernetes.io/hostname: n8n.jterrazz.com
    external-dns.alpha.kubernetes.io/target: "jterrazz-vps.tail77a797.ts.net"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.jterrazz.com`)
      kind: Rule
      middlewares:
        - name: private-access
          namespace: platform-networking
      services:
        - name: n8n
          port: 5678
  tls:
    secretName: n8n-tls
