{{- if eq (include "app.envExists" .) "true" -}}
{{- if .Values.spec.storage -}}
{{- $appName := include "app.name" . -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $appName }}-{{ .Values.environment }}-data
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.spec.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s-data/{{ $appName }}-{{ .Values.environment }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $appName }}-data
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.spec.storage.size }}
  storageClassName: manual
  volumeName: {{ $appName }}-{{ .Values.environment }}-data
{{- end }}
{{- end }}
