otelCollectorEndpoint: signoz-otel-collector.platform-observability:4317

presets:
  otlpExporter:
    enabled: true
  hostMetrics:
    enabled: true
    collectionInterval: 60s
  kubeletMetrics:
    enabled: true
    collectionInterval: 60s
    insecureSkipVerify: true
  clusterMetrics:
    enabled: true
  logsCollection:
    enabled: false

otelAgent:
  resources:
    requests:
      cpu: 10m
      memory: 51Mi
    limits:
      memory: 128Mi

otelDeployment:
  resources:
    requests:
      cpu: 10m
      memory: 49Mi
    limits:
      memory: 128Mi
