---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-tls
spec:
  secretName: portainer-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - portainer.jterrazz.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: portainer.jterrazz.com
    external-dns.alpha.kubernetes.io/target: "jterrazz-vps.tail77a797.ts.net"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.jterrazz.com`)
      kind: Rule
      middlewares:
        - name: private-access
          namespace: platform-networking
      services:
        - name: portainer
          port: 9000
  tls:
    secretName: portainer-tls
