# Docker Registry - Private container registry
# NOTE: This file is templated by Ansible with secrets from Pulumi
# See: ansible/templates/kubernetes/registry.yaml.j2

# Placeholder - will be replaced by Ansible template
